defaults:
  - polygraph_eval_triviaqa_default_instruct
  - top1_processing
  - _self_

experiment_name: triviaqa_empirical_baselines

description: "Answer the following question."
few_shot_prompt: "Question: {question}\nGuess: {answer}"
prompt: "Question: {question}\n"
max_new_tokens: 10000

use_tok_ue: true
include_whitebox_ue: true
additional_estimators: 
  - module: lm_polygraph.estimators.token_sar
    class_name: TokenSAR
    kwargs: {}
  - module: lm_polygraph.estimators.perplexity
    class_name: Perplexity
    kwargs: {}